version: '3'

services:
   jupyter:
      image: jupyter/minimal-notebook
      environment:
         - GEN_CERT=yes
      ports:
         - "8888:8888"
      volumes:
         - /home/ubuntu/review/bdp2-midterm/work:/home/jovyan/work

   portainer:
      image: portainer/portainer
      command: -H unix:///var/run/docker.sock
      restart: always
      container_name: portainer_
      ports:
         - 9000:9000
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - portainer_data:/data      

volumes:
    portainer_data:
